version: '3.3'
services:
  
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./data/db:/var/lib/postgres/data/
    env_file:
      - ./.env
  web:
    image: maltassarus/foodgram:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    image: maltassarus/foodgram:latest
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/

volumes:
  static_value:
  media_value: